analyzer:
  exclude:
    - intl_phone_number_input/**
    - swipeable_card_stack/**
    - lib/**.g.dart
    - mercury_audio_player/**
    - mobile_system_proxy/**
    - flog/**
    - test/generated_migrations/**
    - test/db/**

  errors:
    always_declare_return_types: error
    missing_return: error
    missing_required_param: error

linter:
  rules:
    - always_declare_return_types
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_types_as_parameter_names
    - camel_case_extensions
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - library_prefixes
    - no_duplicate_case_values
    - omit_local_variable_types
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_spread_collections
    - recursive_getters
    - slash_for_doc_comments
    - type_init_formals
    - unnecessary_null_in_if_null_operators
    - unrelated_type_equality_checks
    - valid_regexps
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_constructors_over_static_methods
    - use_full_hex_values_for_flutter_colors
    - avoid_returning_null_for_future
    - hash_and_equals
    - prefer_void_to_null
    - use_key_in_widget_constructors
    - avoid_unnecessary_containers
    - file_names
    - prefer_single_quotes
    - sort_constructors_first
    - unnecessary_new
