// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5uyl2G5OduAyE23LNQheYPoVSiAicRdg',
    appId: '1:991933001317:android:36087a85fcf69e986ee08c',
    messagingSenderId: '991933001317',
    projectId: 'v24service',
    storageBucket: 'v24service.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYdPUsqhoHwhzBcQdEH33iMSlLG7PULX8',
    appId: '1:991933001317:ios:bfaec80f90c00a7f6ee08c',
    messagingSenderId: '991933001317',
    projectId: 'v24service',
    storageBucket: 'v24service.appspot.com',
    iosClientId: '991933001317-od9shb1flnffebl184juatfrkc2b8796.apps.googleusercontent.com',
    iosBundleId: 'com.v24TeacherApp.ios',
  );
}
